appProjects:
  - name: theme-park-api-dev
    gitUrl: 'https://github.com/RyanMillerC/openshift-path-based-routing.git'
    applications:
      - name: hershey-park
        gitPath: '.'
      - name: kings-dominion
        gitPath: '.'
      - name: six-flags
        gitPath: '.'
