appProjects:
    # Name will be used for the Argo CD AppProject and the Namespace the
    # applications will be deployed into
  - name: theme-park-api-dev

    # Description for the project
    description: "Development deployment of Theme Park API"

    # Display name for the project
    displayName: "Theme Park API - Dev"

    # URL to a Git repo with application Helm charts for this project. This URL
    # should end in ".git"
    gitUrl: "https://github.com/RyanMillerC/theme-park-api-chart.git"

    # Git branch to pull charts from. Default: "main"
    gitBranch: main

    # Helm values file to use relative to each helm chart. Default: "values.yaml"
    valuesFile: dev.values.yaml

    # List of applications to deploy into the project
    applications:
        # Name of the application. THIS MUST BE UNIQUE! Even if deployed into a
        # different project, Argo CD Application names must be unique
      - name: hershey-park-dev

        # Path inside the project gitUrl to the Helm chart. Use "." if the
        # chart is in the root of the repo. Use a relative path otherwise
        gitPath: './hershey-park'

      - name: kings-dominion-dev
        gitPath: './kings-dominion'
      - name: six-flags-dev
        gitPath: './six-flags'

  # Only required options are provided in this block
  # - name: theme-park-api-test
  #   description: "Test deployment of Theme Park API"
  #   displayName: "Theme Park API - Test"
  #   gitUrl: "https://github.com/RyanMillerC/theme-park-api-chart.git"
  #   valuesFile: test.values.yaml
  #   applications:
  #     - name: hershey-park-test
  #       gitPath: './hershey-park'
  #     - name: kings-dominion-test
  #       gitPath: './kings-dominion'
  #     - name: six-flags-test
  #       gitPath: './six-flags'
