applications:
  - namespace: theme-park-api-dev
    gitUrl: https://github.com/RyanMillerC/openshift-path-based-routing.git
    gitPath: '.'
  - namespace: theme-park-api-test
    gitUrl: https://github.com/RyanMillerC/openshift-path-based-routing.git
    gitPath: '.'
