{{ range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .namespace }}
  namespace: openshift-gitops
spec:
  destinations:
    - name: in-cluster
      namespace: {{ .namespace }}
  sourceRepos:
    - {{ .gitUrl }}
{{ end }}
